Experiment:
    version: 2.0

    SpatialQuery: 
        type: kd-tree
        test_visibility: false

    Common: 
        time_step: 0.1
    OpenSteer: 
        max_force: 8
        leak_through: 0.1
        reaction_time: 0.5
    GCF: 
        reaction_time: 0.5
        max_agent_dist: 2
        max_agent_force: 3
        agent_interp_width: 0.1
        nu_agent: 0.35
    Helbing: 
        agent_scale: 2000
        obstacle_scale: 4000
        reaction_time: 0.5
        body_force: 1200
        friction: 2400
        force_distance: 0.015
    Johansson: 
        agent_scale: 25
        obstacle_scale: 35
        reaction_time: 0.5
        force_distance: 0.15
        stride_time: 0.5
    Karamouzas: 
        orient_weight: 0.8
        fov: 200
        reaction_time: 0.4
        wall_steepness: 2
        wall_distance: 2
        colliding_count: 5
        d_min: 1
        d_mid: 8
        d_max: 10
        agent_force: 4
    Zanlungo: 
        agent_scale: 2000
        obstacle_scale: 4000
        reaction_time: 0.5
        force_distance: 0.005
    Dummy: 
        stddev: 1.0

    AgentProfilePed: 
        name: group1
        OpenSteer: 
            tau: 3
            tauObst: 6
        Common: 
            max_angle_vel: 180
            max_neighbors: 10
            obstacleSet: 1
            neighbor_dist: 5
            r: 0.25
            class: 4
            pref_speed: 1.04
            max_speed: 2
            max_accel: 5
            external: 0
        PedVO: 
            factor: 1.57
            buffer: 0.9
            tau: 3
            tauObst: 0.1
            turningBias: 1.0
        GCF: 
            stand_depth: 0.18
            move_scale: 0.53
            slow_width: 0.25
            sway_change: 0.05
            orient_weight: 0.75
        Helbing: 
            mass: 80
        Johansson: 
            fov_weight: 0.16
        Karamouzas: 
            personal_space: 0.69
            anticipation: 8
        ORCA: 
            tau: 3
            tauObst: 0.15
        Zanlungo: 
            mass: 80
            orient_weight: 0.75

    AgentProfileRob: 
        name: robot
        inherits: group1        
        ORCA: 
            tau: 3
            tauObst: 0.15
        Common: 
            class: 3
            r: 0.3
            external: 1
            start_angle: -0.8587
            end_angle: 0.8587
            increment: 0.0017453
            range_max: 50
        Helbing: 
            mass: 320

BFSM:
    StateWalk: 
        GoalSelector:
            type: random
            goal_set: 0
            per_agent: 1
        VelComponent: 
            type: goal
        Action:
            type: offset_property
            property: priority
            dist: c
            value: 0.0
            exit_reset: 0
        name: Walk
        final: 0
    StateArrive:
        VelComponent: 
            type: zero
        Action: 
            type: offset_property
            property: priority
            dist: c
            value: 1.0
            exit_reset: 0
        name: Arrive
        final: 0
    StateDecide:     
        VelComponent: 
            type: zero
        name: Decide
        final: 0
    StateHappy:
        VelComponent: 
            type: zero
        name: Happy
        final: 0
    StateAngry:     
        VelComponent: 
            type: zero
        name: Angry
        final: 0

    TransitionArrive:
        from: Walk
        to: Arrive    
        Condition: 
            type: goal_reached
            distance: 0.4
    TransitionDecide:
        from: Arrive
        to: Decide
        Condition: 
            type: timer
            dist: u
            min: 2
            max: 4
            seed: 5
            per_agent: 1
    TransitionHappyAngry:
        from: Decide
        Condition: 
            type: auto
        Target: 
            type: prob
            StateHappy: 
                name: Happy
                weight: 1.0
            StateAngry:             
                name: Angry
                weight: 1.0
    TransitionWalkHappy:
        from: Happy
        to: Walk
        Condition: 
            type: timer
            dist: u
            min: 4
            max: 6
            seed: 6
            per_agent: 1
    TransitionWalkAngry:
        from: Angry
        to: Walk
        Condition: 
            type: timer
            dist: u
            min: 1
            max: 2
            seed: 7
            per_agent: 1
